name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint pylint-django anybadge
    - name: Analysing the code with pylint
      run: |
        pylint --exit-zero --load-plugins pylint_django --django-settings-module=onviz_main.settings $(git ls-files '*.py') | tee pylint.log
        PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./pylint.log)
    - name: Pylint badge
      uses: RubbaBoy/BYOB@v1.3.0
      with:
        NAME: pylint
        LABEL: 'pylint'
        STATUS: ${{ env.PYLINT_SCORE }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
